version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: platirix-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: platirix
      POSTGRES_PASSWORD: platirix
      POSTGRES_DB: platirix
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
